### ISSUE TITLE
Always filter as far left in your pipeline as possible

### ISSUE THREAD

**Issue by guyrleech** [RMITBLOG/MSIX_APP_ATTACH#2]
Your Get-CimInstance call will return all win32_volume objects and then filter them whereas the more efficient way to do this kind of query is to use the -Filter parameter to Get-CimInstance

Get-CimInstance -classname win32_volume -Filter "filesystem = 'cimfs'" | Select-Object -Property name, filesystem, DeviceID

**Comment by RMITBLOG** [comment]
Thanks, Guy. This is appreciated.

**Comment by RMITBLOG** [comment]
Get-CimInstance
